#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

# Check if anything to format
if [[ "${STAGED_GO_FILES}" = "" ]]; then
  exit 0
fi

# Format Go code
for FILE in ${STAGED_GO_FILES}; do
  go fmt "${FILE}"
  git add "${FILE}"
done

exit 0
